config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # Read all
  root to: "lists#index"
  resources :lists, only: [ :index, :show, :new, :create, :destroy ] do
    resources :bookmarks, only: [ :new, :create ]
  end
    resources :bookmarks, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, uniqueness: { scope: :list }
  validates :comment, length:{ minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :bookmarks
    validates :title, uniqueness: true, presence: true
    validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :find_list, only: [ :new, :create ]

  def new
    @bookmark = Bookmark.new
  end
  
  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end
  
  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to root_path
  end
  
  private
  
  def find_list
    @list = List.find(params[:list_id])
  end
  
  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
    redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>blank</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <div class="row cards">
    <% @lists.each do |list| %>   
    <h4><%= link_to list.name, list_path(list)%></h4>
    <% end %>
  </div>
</div>
<br>
<br>
<div class="container">
  <div class="row cards">
  <h1><%= link_to "create_new_list", new_list_path %></h1>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
<h1>Create your list</h1>
</div>


<div class="container">
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name, placeholder: 'Add a list' %>
    <%= f.submit "Create" %>
  <% end %>
</div>

<div class="container">
<%= link_to "back_to_overview", root_path %>
</div>

app/views/lists/show.html.erb
<div class="container">
<h2><%= @list.name %></h2>
<%= link_to "Delete list?", list_path(@list), data: {turbo_method: :delete, turbo_confirm:"are you sure?"}, id: "delete-link", class: "hidden" %>
</div>
<br>
<br>

<div class="container">
  <h1>Movies</h1>
</div>

<div class="container">
  <% @list.bookmarks.each do |bookmark| %>
    <%= image_tag bookmark.movie.poster_url, alt: "movie poster" %>
    <h3><%= bookmark.movie.title %></h3>
    <h4>Rating : <%= "⭐️" * bookmark.movie.rating %></h4>
    <h5> <%= bookmark.movie.overview %> </h5>

    <hr>

    <h2>Review</h2>
    <p><%= bookmark.comment %></p>
    <hr>
     <%= link_to "delete bookmark", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm:"are you sure?"}, id:"delete-bookmark", class: "hidden" %>
  <% end %>
</div>
<br>
<br>
<div class="container">
  <h2>Add a new movie</h2>
  <%= simple_form_for [ @list, @bookmark ] do |f| %>
    <%= f.input :comment, placeholder: 'Add comment' %>
    <%= f.association :movie %>
    <%= f.submit "Add movie" %>
  <% end %>
</div>

<div class="container">
<%= link_to "back_to_overview", root_path %>
</div>